### ISSUE TITLE
Fails to compile with GCC 4.9.3: main.c:23:18: error: ‘optarg’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by hartwork** [whitfin/siphash-c#3]
```
# git clone https://github.com/zackehh/siphash-c.git
Cloning into 'siphash-c'...
remote: Counting objects: 21, done.
remote: Total 21 (delta 0), reused 0 (delta 0), pack-reused 21
Unpacking objects: 100% (21/21), done.

# cd siphash-c/

# make
mkdir -p build
cc -g -O3 -ansi -pedantic -Wall -Wextra main.c src/siphash.c -o build/siphash
main.c: In function ‘main’:
main.c:20:3: warning: implicit declaration of function ‘getopt’ [-Wimplicit-function-declaration]
   while ((option = getopt(argc, argv, "f:k:i:c:d:")) != -1) {
   ^
main.c:23:18: error: ‘optarg’ undeclared (first use in this function)
         c = atoi(optarg);
                  ^
main.c:23:18: note: each undeclared identifier is reported only once for each function it appears in
main.c:37:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(input, (size_t) filelen, 1, fileptr);
         ^
make: *** [Makefile:11: siphash] Error 1

# gcc -dumpversion
4.9.3
```

**Comment by hartwork** [comment]
Adding `#include <getopt.h>` fixes compilation for me.

**Comment by whitfin** [comment]
@hartwork want to PR this change? :) I can add it if not.

**Comment by haileeshen** [comment]
Good Job, THX.

**Comment by hartwork** [comment]
Fixed in ffbec559b35397fe12c1746207b7823a70c9c28a
